---
title: "gt_summary_pp_slides"
author: "Chris Rowland"
format: pptx
editor: visual
---

```{r setup}
#| include: false
library(gtsummary)
library(gt)

```

## Example from Reference Doc

::: columns
::: {.column width="50%"}
```{r}
#| echo: true
#| results: false
#| message: false
#| warning: false
#| label: tbl_strata_response_by_grade
tbl_strata_response_by_grade <-
  trial %>%
  select(grade, response) %>%
  mutate(grade = paste("Grade", grade)) %>%
  tbl_strata2(
    strata = grade,
    .tbl_fun =
      ~.x %>%
      tbl_summary(
        label = list(response = .y),
        missing = "no",
        statistic = response ~ "{p}%"
      ) %>%
      add_ci(pattern = "{stat} ({ci})") %>%
     modify_header(stat_0 = "**Rate (95% CI)**") %>%
     modify_footnote(stat_0 = NA),
    .combine_with = "tbl_stack",
    .combine_args = list(group_header = NULL),
    .quiet = TRUE
  ) %>%
  modify_caption("**Response Rate by Grade**") %>%
  as_gt()

```
:::

::: {.column width="50%"}
```{r}
#| echo: false

tbl_strata_response_by_grade
```
:::
:::
